version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    restart: always


  web:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - db
    image: recipe_service
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    command: >
      bash -c "alembic upgrade head && python -m uvicorn main:app --host 0.0.0.0 --proxy-headers --port 8000"
    restart: always

volumes:
  postgres_data:
