"""“remove_image_in_rating”

Revision ID: c89a1181206a
Revises: 39c4d5161253
Create Date: 2023-04-24 15:33:43.530802

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c89a1181206a"
down_revision = "39c4d5161253"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
